// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.4.1.34438 Microsoft Reciprocal License (Ms-RL) 
//    <NameSpace>Puch.JPK</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net40</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><EnableInitializeFields>True</EnableInitializeFields>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace Puch.JPK
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;


    public partial class JPK
    {

        private TNaglowek naglowekField;

        private JPKPodmiot1 podmiot1Field;

        private List<JPKSprzedazWiersz> sprzedazWierszField;

        private JPKSprzedazCtrl sprzedazCtrlField;

        private List<JPKZakupWiersz> zakupWierszField;

        private JPKZakupCtrl zakupCtrlField;

        public JPK()
        {
            this.zakupCtrlField = new JPKZakupCtrl();
            this.zakupWierszField = new List<JPKZakupWiersz>();
            this.sprzedazCtrlField = new JPKSprzedazCtrl();
            this.sprzedazWierszField = new List<JPKSprzedazWiersz>();
            this.podmiot1Field = new JPKPodmiot1();
            this.naglowekField = new TNaglowek();
        }

        public TNaglowek Naglowek
        {
            get
            {
                return this.naglowekField;
            }
            set
            {
                this.naglowekField = value;
            }
        }

        public JPKPodmiot1 Podmiot1
        {
            get
            {
                return this.podmiot1Field;
            }
            set
            {
                this.podmiot1Field = value;
            }
        }

        [XmlElement]
        public List<JPKSprzedazWiersz> SprzedazWiersz
        {
            get
            {
                return this.sprzedazWierszField;
            }
            set
            {
                this.sprzedazWierszField = value;
            }
        }

        public JPKSprzedazCtrl SprzedazCtrl
        {
            get
            {
                return this.sprzedazCtrlField;
            }
            set
            {
                this.sprzedazCtrlField = value;
            }
        }

        [XmlElement]
        public List<JPKZakupWiersz> ZakupWiersz
        {
            get
            {
                return this.zakupWierszField;
            }
            set
            {
                this.zakupWierszField = value;
            }
        }

        public JPKZakupCtrl ZakupCtrl
        {
            get
            {
                return this.zakupCtrlField;
            }
            set
            {
                this.zakupCtrlField = value;
            }
        }
    }

    public partial class TNaglowek
    {

        private TNaglowekKodFormularza kodFormularzaField;

        private sbyte wariantFormularzaField;

        private short celZlozeniaField;

        private System.DateTime dataWytworzeniaJPKField;

        private System.DateTime dataOdField;

        private System.DateTime dataDoField;

        private string nazwaSystemuField;

        public TNaglowek()
        {
            this.kodFormularzaField = new TNaglowekKodFormularza();
        }

        public TNaglowekKodFormularza KodFormularza
        {
            get
            {
                return this.kodFormularzaField;
            }
            set
            {
                this.kodFormularzaField = value;
            }
        }

        public sbyte WariantFormularza
        {
            get
            {
                return this.wariantFormularzaField;
            }
            set
            {
                this.wariantFormularzaField = value;
            }
        }

        public short CelZlozenia
        {
            get
            {
                return this.celZlozeniaField;
            }
            set
            {
                this.celZlozeniaField = value;
            }
        }

        [XmlElement(DataType = "dateTime")]
        public System.DateTime DataWytworzeniaJPK
        {
            get
            {
                return this.dataWytworzeniaJPKField;
            }
            set
            {
                this.dataWytworzeniaJPKField = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime DataOd
        {
            get
            {
                return this.dataOdField;
            }
            set
            {
                this.dataOdField = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime DataDo
        {
            get
            {
                return this.dataDoField;
            }
            set
            {
                this.dataDoField = value;
            }
        }

        public string NazwaSystemu
        {
            get
            {
                return this.nazwaSystemuField;
            }
            set
            {
                this.nazwaSystemuField = value;
            }
        }
    }

    public partial class TNaglowekKodFormularza
    {

        private string kodSystemowyField;

        private string wersjaSchemyField;

        private TKodFormularza valueField;

        public TNaglowekKodFormularza()
        {
            this.kodSystemowyField = "JPK_VAT (3)";
            this.wersjaSchemyField = "1-1";
        }

        [XmlAttribute]
        public string kodSystemowy
        {
            get
            {
                return this.kodSystemowyField;
            }
            set
            {
                this.kodSystemowyField = value;
            }
        }

        [XmlAttribute]
        public string wersjaSchemy
        {
            get
            {
                return this.wersjaSchemyField;
            }
            set
            {
                this.wersjaSchemyField = value;
            }
        }

        [System.Xml.Serialization.XmlTextAttribute()]
        public TKodFormularza Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    public enum TKodFormularza
    {

        /// <remarks/>
        JPK_VAT,
    }

    public partial class JPKPodmiot1
    {

        private string nIPField;

        private string pelnaNazwaField;

        private string emailField;

        public string NIP
        {
            get
            {
                return this.nIPField;
            }
            set
            {
                this.nIPField = value;
            }
        }

        public string PelnaNazwa
        {
            get
            {
                return this.pelnaNazwaField;
            }
            set
            {
                this.pelnaNazwaField = value;
            }
        }

        [DefaultValue("")]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    public partial class JPKSprzedazWiersz
    {

        private uint lpSprzedazyField;

        private string nrKontrahentaField;

        private string nazwaKontrahentaField;

        private string adresKontrahentaField;

        private string dowodSprzedazyField;

        private System.DateTime dataWystawieniaField;

        private System.DateTime dataSprzedazyField;

        private decimal k_10Field;

        private decimal k_11Field;

        private decimal k_12Field;

        private decimal k_13Field;

        private decimal k_14Field;

        private decimal k_15Field;

        private decimal k_16Field;

        private decimal k_17Field;

        private decimal k_18Field;

        private decimal k_19Field;

        private decimal k_20Field;

        private decimal k_21Field;

        private decimal k_22Field;

        private decimal k_23Field;

        private decimal k_24Field;

        private decimal k_25Field;

        private decimal k_26Field;

        private decimal k_27Field;

        private decimal k_28Field;

        private decimal k_29Field;

        private decimal k_30Field;

        private decimal k_31Field;

        private decimal k_32Field;

        private decimal k_33Field;

        private decimal k_34Field;

        private decimal k_35Field;

        private decimal k_36Field;

        private decimal k_37Field;

        private decimal k_38Field;

        private decimal k_39Field;

        public uint LpSprzedazy
        {
            get
            {
                return this.lpSprzedazyField;
            }
            set
            {
                this.lpSprzedazyField = value;
            }
        }

        public string NrKontrahenta
        {
            get
            {
                return this.nrKontrahentaField;
            }
            set
            {
                this.nrKontrahentaField = value;
            }
        }

        public string NazwaKontrahenta
        {
            get
            {
                return this.nazwaKontrahentaField;
            }
            set
            {
                this.nazwaKontrahentaField = value;
            }
        }

        public string AdresKontrahenta
        {
            get
            {
                return this.adresKontrahentaField;
            }
            set
            {
                this.adresKontrahentaField = value;
            }
        }

        public string DowodSprzedazy
        {
            get
            {
                return this.dowodSprzedazyField;
            }
            set
            {
                this.dowodSprzedazyField = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime DataWystawienia
        {
            get
            {
                return this.dataWystawieniaField;
            }
            set
            {
                this.dataWystawieniaField = value;
            }
        }

        [XmlElement(DataType = "date")]
        [DefaultValue(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime DataSprzedazy
        {
            get
            {
                return this.dataSprzedazyField;
            }
            set
            {
                this.dataSprzedazyField = value;
            }
        }

        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_10
        {
            get
            {
                return this.k_10Field;
            }
            set
            {
                this.k_10Field = value;
            }
        }
        
        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_11
        {
            get
            {
                return this.k_11Field;
            }
            set
            {
                this.k_11Field = value;
            }
        }
        
        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_12
        {
            get
            {
                return this.k_12Field;
            }
            set
            {
                this.k_12Field = value;
            }
        }
        
        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_13
        {
            get
            {
                return this.k_13Field;
            }
            set
            {
                this.k_13Field = value;
            }
        }

        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_14
        {
            get
            {
                return this.k_14Field;
            }
            set
            {
                this.k_14Field = value;
            }
        }

        public decimal K_15
        {
            get
            {
                return this.k_15Field;
            }
            set
            {
                this.k_15Field = value;
            }
        }

        public decimal K_16
        {
            get
            {
                return this.k_16Field;
            }
            set
            {
                this.k_16Field = value;
            }
        }

        public decimal K_17
        {
            get
            {
                return this.k_17Field;
            }
            set
            {
                this.k_17Field = value;
            }
        }

        public decimal K_18
        {
            get
            {
                return this.k_18Field;
            }
            set
            {
                this.k_18Field = value;
            }
        }

        public decimal K_19
        {
            get
            {
                return this.k_19Field;
            }
            set
            {
                this.k_19Field = value;
            }
        }

        public decimal K_20
        {
            get
            {
                return this.k_20Field;
            }
            set
            {
                this.k_20Field = value;
            }
        }

        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_21
        {
            get
            {
                return this.k_21Field;
            }
            set
            {
                this.k_21Field = value;
            }
        }

        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_22
        {
            get
            {
                return this.k_22Field;
            }
            set
            {
                this.k_22Field = value;
            }
        }

        public decimal K_23
        {
            get
            {
                return this.k_23Field;
            }
            set
            {
                this.k_23Field = value;
            }
        }

        public decimal K_24
        {
            get
            {
                return this.k_24Field;
            }
            set
            {
                this.k_24Field = value;
            }
        }

        public decimal K_25
        {
            get
            {
                return this.k_25Field;
            }
            set
            {
                this.k_25Field = value;
            }
        }

        public decimal K_26
        {
            get
            {
                return this.k_26Field;
            }
            set
            {
                this.k_26Field = value;
            }
        }

        public decimal K_27
        {
            get
            {
                return this.k_27Field;
            }
            set
            {
                this.k_27Field = value;
            }
        }

        public decimal K_28
        {
            get
            {
                return this.k_28Field;
            }
            set
            {
                this.k_28Field = value;
            }
        }

        public decimal K_29
        {
            get
            {
                return this.k_29Field;
            }
            set
            {
                this.k_29Field = value;
            }
        }

        public decimal K_30
        {
            get
            {
                return this.k_30Field;
            }
            set
            {
                this.k_30Field = value;
            }
        }

        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_31
        {
            get
            {
                return this.k_31Field;
            }
            set
            {
                this.k_31Field = value;
            }
        }

        public decimal K_32
        {
            get
            {
                return this.k_32Field;
            }
            set
            {
                this.k_32Field = value;
            }
        }

        public decimal K_33
        {
            get
            {
                return this.k_33Field;
            }
            set
            {
                this.k_33Field = value;
            }
        }

        public decimal K_34
        {
            get
            {
                return this.k_34Field;
            }
            set
            {
                this.k_34Field = value;
            }
        }

        public decimal K_35
        {
            get
            {
                return this.k_35Field;
            }
            set
            {
                this.k_35Field = value;
            }
        }

        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_36
        {
            get
            {
                return this.k_36Field;
            }
            set
            {
                this.k_36Field = value;
            }
        }


        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_37
        {
            get
            {
                return this.k_37Field;
            }
            set
            {
                this.k_37Field = value;
            }
        }
        
        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_38
        {
            get
            {
                return this.k_38Field;
            }
            set
            {
                this.k_38Field = value;
            }
        }


        [DefaultValue(typeof(Decimal), "0")]
        public decimal K_39
        {
            get
            {
                return this.k_39Field;
            }
            set
            {
                this.k_39Field = value;
            }
        }
                
    }

    public partial class JPKSprzedazCtrl
    {

        private uint liczbaWierszySprzedazyField;

        private decimal podatekNaleznyField;

        public uint LiczbaWierszySprzedazy
        {
            get
            {
                return this.liczbaWierszySprzedazyField;
            }
            set
            {
                this.liczbaWierszySprzedazyField = value;
            }
        }

        public decimal PodatekNalezny
        {
            get
            {
                return this.podatekNaleznyField;
            }
            set
            {
                this.podatekNaleznyField = value;
            }
        }
    }

    public partial class JPKZakupWiersz
    {

        private uint lpZakupuField;

        private string nrDostawcyField;

        private string nazwaDostawcyField;

        private string adresDostawcyField;

        private string dowodZakupuField;

        private System.DateTime dataZakupuField;

        private System.DateTime dataWplywuField;

        private decimal k_43Field;

        private decimal k_44Field;

        private decimal k_45Field;

        private decimal k_46Field;

        private decimal k_47Field;

        private decimal k_48Field;

        private decimal k_49Field;

        private decimal k_50Field;

        public uint LpZakupu
        {
            get
            {
                return this.lpZakupuField;
            }
            set
            {
                this.lpZakupuField = value;
            }
        }

        public string NrDostawcy
        {
            get
            {
                return this.nrDostawcyField;
            }
            set
            {
                this.nrDostawcyField = value;
            }
        }

        public string NazwaDostawcy
        {
            get
            {
                return this.nazwaDostawcyField;
            }
            set
            {
                this.nazwaDostawcyField = value;
            }
        }

        public string AdresDostawcy
        {
            get
            {
                return this.adresDostawcyField;
            }
            set
            {
                this.adresDostawcyField = value;
            }
        }

        public string DowodZakupu
        {
            get
            {
                return this.dowodZakupuField;
            }
            set
            {
                this.dowodZakupuField = value;
            }
        }

        [XmlElement(DataType = "date")]
        public System.DateTime DataZakupu
        {
            get
            {
                return this.dataZakupuField;
            }
            set
            {
                this.dataZakupuField = value;
            }
        }

        [XmlElement(DataType = "date")]
        [DefaultValue(typeof(System.DateTime), "0001-01-01")]
        public System.DateTime DataWplywu
        {
            get
            {
                return this.dataWplywuField;
            }
            set
            {
                this.dataWplywuField = value;
            }
        }

        public decimal K_43
        {
            get
            {
                return this.k_43Field;
            }
            set
            {
                this.k_43Field = value;
            }
        }

        public decimal K_44
        {
            get
            {
                return this.k_44Field;
            }
            set
            {
                this.k_44Field = value;
            }
        }

        public decimal K_45
        {
            get
            {
                return this.k_45Field;
            }
            set
            {
                this.k_45Field = value;
            }
        }

        public decimal K_46
        {
            get
            {
                return this.k_46Field;
            }
            set
            {
                this.k_46Field = value;
            }
        }

        [DefaultValue(typeof(decimal), "0")]
        public decimal K_47
        {
            get
            {
                return this.k_47Field;
            }
            set
            {
                this.k_47Field = value;
            }
        }

        [DefaultValue(typeof(decimal), "0")]
        public decimal K_48
        {
            get
            {
                return this.k_48Field;
            }
            set
            {
                this.k_48Field = value;
            }
        }

        [DefaultValue(typeof(decimal), "0")]
        public decimal K_49
        {
            get
            {
                return this.k_49Field;
            }
            set
            {
                this.k_49Field = value;
            }
        }

        [DefaultValue(typeof(decimal), "0")]
        public decimal K_50
        {
            get
            {
                return this.k_50Field;
            }
            set
            {
                this.k_50Field = value;
            }
        }

    }

    public partial class JPKZakupCtrl
    {

        private uint liczbaWierszyZakupowField;

        private decimal podatekNaliczonyField;

        public uint LiczbaWierszyZakupow
        {
            get
            {
                return this.liczbaWierszyZakupowField;
            }
            set
            {
                this.liczbaWierszyZakupowField = value;
            }
        }

        public decimal PodatekNaliczony
        {
            get
            {
                return this.podatekNaliczonyField;
            }
            set
            {
                this.podatekNaliczonyField = value;
            }
        }
    }
}
